### ISSUE TITLE
Unable to generate IPA on fresh checkout of branch `release-9.5.3`

### ISSUE THREAD

**Issue by shivanraptor** [TelegramMessenger/Telegram-iOS#1058]
### Checklist
- [X] I am reporting an issue in existing functionality that does not work as intended
- [X] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
I cannot generate IPA on fresh checkout of branch `release-9.5.3`, using the same settings of `release-9.4`

### Expected Behavior
The IPA should be generated without error.

### Actual Behavior
The following error appears:
```
ERROR: /Users/adv/Documents/workspace/Xcode/xCodeProjects/telegram/release-9.5.3/Telegram/BUILD:1448:14: Processing and signing WidgetExtension failed: (Exit 1): process-and-sign--1295105435.sh failed: error executing command 
  (cd /private/var/tmp/_bazel_adv/41d096bc4f8e052b19e6258c124586e7/execroot/__main__ && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneOS \
    APPLE_SDK_VERSION_OVERRIDE=16.2 \
    XCODE_VERSION_OVERRIDE=14.2.0.14C18 \
  bazel-out/applebin_ios-ios_armv7-opt-ST-5b7531beec20/bin/Telegram/WidgetExtension-intermediates/process-and-sign--1295105435.sh should_sign should_process should_compress)
# Configuration: cc82698ade6dde725501929267742da50515e16b13c5c2513ed32bea0175bd07
# Execution platform: @local_config_platform//:host
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_adv/41d096bc4f8e052b19e6258c124586e7/execroot/__main__/bazel-out/darwin-opt-exec-2B5CBBC6-ST-8bd7c7db9774/bin/external/build_bazel_rules_apple/tools/codesigningtool/codesigningtool.runfiles/build_bazel_rules_apple/tools/codesigningtool/codesigningtool.py", line 418, in <module>
    sys.exit(main(generate_arg_parser().parse_args()))
  File "/private/var/tmp/_bazel_adv/41d096bc4f8e052b19e6258c124586e7/execroot/__main__/bazel-out/darwin-opt-exec-2B5CBBC6-ST-8bd7c7db9774/bin/external/build_bazel_rules_apple/tools/codesigningtool/codesigningtool.runfiles/build_bazel_rules_apple/tools/codesigningtool/codesigningtool.py", line 413, in main
    _invoke_codesign(args.codesign, identity, args.entitlements, args.force,
  File "/private/var/tmp/_bazel_adv/41d096bc4f8e052b19e6258c124586e7/execroot/__main__/bazel-out/darwin-opt-exec-2B5CBBC6-ST-8bd7c7db9774/bin/external/build_bazel_rules_apple/tools/codesigningtool/codesigningtool.runfiles/build_bazel_rules_apple/tools/codesigningtool/codesigningtool.py", line 80, in _invoke_codesign
    _, stdout, stderr = execute.execute_and_filter_output(cmd,
  File "/private/var/tmp/_bazel_adv/41d096bc4f8e052b19e6258c124586e7/execroot/__main__/bazel-out/darwin-opt-exec-2B5CBBC6-ST-8bd7c7db9774/bin/external/build_bazel_rules_apple/tools/codesigningtool/codesigningtool.runfiles/build_bazel_rules_apple/tools/wrapper_common/execute.py", line 103, in execute_and_filter_output
    raise subprocess.CalledProcessError(proc.returncode, cmd_args)
subprocess.CalledProcessError: Command '['/usr/bin/codesign', '--sign', '6770975FEA348823FF842D5A2534F31D8C8B2B24', '--generate-entitlement-der', '--entitlements', 'bazel-out/applebin_ios-ios_armv7-opt-ST-5b7531beec20/bin/Telegram/WidgetExtension_entitlements.entitlements', '--force', 'bazel-out/applebin_ios-ios_armv7-opt-ST-5b7531beec20/bin/Telegram/WidgetExtension_archive-root/WidgetExtension.appex']' returned non-zero exit status 1.
ERROR:

error: The specified item could not be found in the keychain.

Target //Telegram:Telegram failed to build
INFO: Elapsed time: 464.763s, Critical Path: 440.60s
INFO: 4576 processes: 2669 disk cache hit, 1050 internal, 857 local.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "/Users/adv/Documents/workspace/Xcode/xCodeProjects/telegram/release-9.5.3/build-system/Make/Make.py", line 1035, in <module>
    build(bazel=bazel_path, arguments=args)
  File "/Users/adv/Documents/workspace/Xcode/xCodeProjects/telegram/release-9.5.3/build-system/Make/Make.py", line 600, in build
    bazel_command_line.invoke_build()
  File "/Users/adv/Documents/workspace/Xcode/xCodeProjects/telegram/release-9.5.3/build-system/Make/Make.py", line 369, in invoke_build
    call_executable(combined_arguments)
  File "/Users/adv/Documents/workspace/Xcode/xCodeProjects/telegram/release-9.5.3/build-system/Make/BuildEnvironment.py", line 81, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/Users/adv/opt/miniconda3/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/bazel', 'build', 'Telegram/Telegram', '--override_repository=build_configuration=/Users/adv/Documents/workspace/Xcode/xCodeProjects/telegram/release-9.5.3/build-input/configuration-repository', '--announce_rc', '--features=swift.use_global_module_cache', '--verbose_failures', '--experimental_remote_cache_async', '--features=swift.skip_function_bodies_for_derived_files', '--jobs=20', '--define=buildNumber=11261', '--define=telegramVersion=9.5.3', '--disk_cache=/Users/adv/telegram-bazel-cache', '-c', 'opt', '--ios_multi_cpus=armv7,arm64', '--watchos_cpus=arm64_32', '--apple_generate_dsym', '--output_groups=+dsyms', '--features=swift.opt_uses_wmo', '--features=swift.opt_uses_osize', '--swiftcopt=-num-threads', '--swiftcopt=1', '--swiftcopt=-j1', '--features=dead_strip', '--objc_enable_binary_stripping', '--apple_bitcode=watchos=embedded']' returned non-zero exit status 1.
```

### Steps to Reproduce
1. Issue the following command to generate IPA as usual:
`USE_BAZEL_VERSION=5.3.1 python3 build-system/Make/Make.py --overrideXcodeVersion --bazel="/usr/local/bin/bazel" --cacheDir="$HOME/telegram-bazel-cache" build --configurationPath="$HOME/telegram-configuration/development-configuration.json" --buildNumber=11261 --configuration=release_universal --codesigningInformationPath="$HOME/telegram-configuration/fake-codesigning"`

2. The following command appears near the signing stage: *error: The specified item could not be found in the keychain.* (detailed console output above)

### Environment
**Device:** `iPhone 13 Pro`
**iOS version**: `16.3.1`
**Xcode version**: `14.2`
**App version:** `9.5.3`

**Comment by ali-fareed** [comment]
Your certificate might have expired. As you can see, the code itself builds fine https://github.com/TelegramMessenger/Telegram-iOS/actions/runs/4419140346/jobs/7747186649
