### ISSUE TITLE
//Telegram:disableExtensions :: Error loading option //Telegram:disableExtensions: no such package 'Telegram': BUILD file not found in any of the following directories.

### ISSUE THREAD

**Issue by jcropsey** [TelegramMessenger/Telegram-iOS#1119]
### Checklist
- [X] I am reporting an issue in existing functionality that does not work as intended
- [X] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Getting an error while following the directions in README.md to build Telegram-iOS.
```
ERROR: Skipping '//Telegram:disableExtensions': no such package 'Telegram': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
```

### Expected Behavior

Telegram-iOS should build correctly.

### Actual Behavior

I get the following output:
```
No matching processes belonging to you were found
ERROR: Skipping '//Telegram:disableExtensions': no such package 'Telegram': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /Users/jcropsey/Telegram-iOS/Telegram
WARNING: Target pattern parsing failed.
ERROR: //Telegram:disableExtensions :: Error loading option //Telegram:disableExtensions: no such package 'Telegram': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /Users/jcropsey/Telegram-iOS/Telegram
Loading: 
Traceback (most recent call last):
  File "build-system/Make/Make.py", line 1037, in <module>
    generate_project(bazel=bazel_path, arguments=args)
  File "build-system/Make/Make.py", line 565, in generate_project
    generate(
  File "/Users/jcropsey/Telegram-iOS/build-system/Make/ProjectGeneration.py", line 184, in generate
    generate_xcodeproj(build_environment, disable_extensions, disable_provisioning_profiles, generate_dsym, configuration_path, bazel_app_arguments, target_name)
  File "/Users/jcropsey/Telegram-iOS/build-system/Make/ProjectGeneration.py", line 44, in generate_xcodeproj
    call_executable(bazel_generate_arguments)
  File "/Users/jcropsey/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 81, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/jcropsey/Telegram-iOS/build-input/bazel-6.1.1-darwin-x86_64', 'run', '//Telegram:Telegram_xcodeproj', '--override_repository=build_configuration=/Users/jcropsey/Telegram-iOS/build-input/configuration-repository', '--//Telegram:disableExtensions', '--//Telegram:disableStripping']' returned non-zero exit status 2.
```

### Steps to Reproduce

1. I downloaded the Telegram repo into `~`.
2. I created the empty Telegram project in `~/Telegram-iOS/Telegram`.
3. I updated the `template_minimal_development_configuration.json` and `versions.json` files as appropriate. XCode version 14.3.
4. From the `~/Telegram-iOS` directory, I run the command 

```
python3 build-system/Make/Make.py \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath=build-system/template_minimal_development_configuration.json \
    --xcodeManagedCodesigning
```

### Environment
**Device:** N/A

**iOS version**: N/A

**App version:** `9.6.3`

** XCode version:** `14.3`

**Comment by alirezarabiei7239** [comment]
Hi, create Telegram project beside Telegram-ios
this will help you

**Comment by WYStudioEx** [comment]
+1
