### ISSUE TITLE
`View in chat` doesn't work as expected for audio files

### ISSUE THREAD

**Issue by andreykaere** [TelegramMessenger/Telegram-iOS#1276]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Describe the issue that you are experiencing

When I prees "view in chat" for audio files, I am just getting redirected to the chat, not to the concrete message.

### Expected Behavior
Tell us what should happen

As it was before, I want to be able to see the message, containing this audio file. 

### Actual Behavior
Tell us what happens instead

I am just getting redirected to the chat, not to the concrete message.

### Steps to Reproduce
1. Start some audio file and leave the chat.
2. Tap on the audio pannel and press "view in chat".
3. You are not redirected to the message, just to the chat.

### Screenshots and Videos 
Remove, if not applicable

### Environment
**Device:** `iPhone`

**iOS version**: `15.3.1`

**App version:** `10.2.2`

**Comment by Satthawut2547** [comment]
No matching processes belonging to you were found
Loading: 
Loading: 
Loading: 1 packages loaded
Analyzing: target //Telegram:Telegram_xcodeproj (1 packages loaded, 0 targets configured)
INFO: Analyzed target //Telegram:Telegram_xcodeproj (1 packages loaded, 1 target configured).
INFO: Found 1 target...
[0 / 4] [Prepa] BazelWorkspaceStatusAction stable-status.txt
Target //Telegram:Telegram_xcodeproj up-to-date:
bazel-bin/Telegram/Telegram_xcodeproj-runner.sh
INFO: Elapsed time: 0.103s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/Telegram/Telegram_xcodeproj-runner.sh

Generating "Telegram/Telegram.xcodeproj"
INFO: Invocation ID: 1905c8ce-d56f-44a8-8ca6-3a4c1df618f0
INFO: Options provided by the client:
Inherited 'common' options: --isatty=0 --terminal_columns=171
INFO: Reading rc options for 'run' from /Users/vakhonakashidze/Projects/Telegram-iOS/xcodeproj.bazelrc:
Inherited 'build' options: --announce_rc --features=swift.use_global_module_cache --verbose_failures --experimental_remote_cache_async --features=swift.enable_batch_mode --swiftcopt=-j9 --define=buildNumber=10000 --define=telegramVersion=10.6.3 --disk_cache=/Users/vakhonakashidze/telegram-bazel-cache --override_repository=build_configuration=/Users/vakhonakashidze/Projects/Telegram-iOS/build-input/configuration-repository --//Telegram:disableExtensions --//Telegram:disableStripping --features=-swift.debug_prefix_map
INFO: Reading rc options for 'run' from /Users/vakhonakashidze/Projects/Telegram-iOS/.bazelrc:
Inherited 'build' options: --action_env=ZERO_AR_DATE=1 --apple_platform_type=ios --enable_platform_specific_config --apple_crosstool_top=@local_config_apple_cc//:toolchain --crosstool_top=@local_config_apple_cc//:toolchain --host_crosstool_top=@local_config_apple_cc//:toolchain --cxxopt=-std=c++17 --per_file_copt=third-party/webrtc/.*.cpp$,@-std=c++17 --per_file_copt=third-party/webrtc/.*.cc$,@-std=c++17 --per_file_copt=third-party/webrtc/.*.mm$,@-std=c++17 --per_file_copt=submodules/LottieMeshSwift/LottieMeshBinding/Sources/.*.mm$,@-std=c++17 --swiftcopt=-whole-module-optimization --per_file_copt=.*.m$,@-fno-objc-msgsend-selector-stubs --per_file_copt=.*.mm$,@-fno-objc-msgsend-selector-stubs --linkopt=-ld_classic --features=debug_prefix_map_pwd_is_dot --features=swift.cacheable_swiftmodules --features=swift.debug_prefix_map --features=swift.enable_vfsoverlays --strategy=Genrule=standalone --spawn_strategy=standalone --strategy=SwiftCompile=standalone --define RULES_SWIFT_BUILD_DUMMY_WORKER=1
INFO: Found applicable config definition build:rules_xcodeproj_generator in file /private/var/tmp/_bazel_vakhonakashidze/4e628adf874771f087c4fbe57dff4b48/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/Telegram/Telegram_xcodeproj.bazelrc: --config=rules_xcodeproj
INFO: Found applicable config definition common:rules_xcodeproj in file /private/var/tmp/_bazel_vakhonakashidze/4e628adf874771f087c4fbe57dff4b48/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/Telegram/Telegram_xcodeproj.bazelrc: --verbose_failures --cache_computed_file_digests=500000
INFO: Found applicable config definition build:rules_xcodeproj in file /private/var/tmp/_bazel_vakhonakashidze/4e628adf874771f087c4fbe57dff4b48/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/Telegram/Telegram_xcodeproj.bazelrc: --compilation_mode=dbg --experimental_action_cache_store_output_metadata --experimental_convenience_symlinks=ignore --define=apple.experimental.tree_artifact_outputs=1 --features=apple.swizzle_absolute_xcttestsourcelocation --features=oso_prefix_is_pwd --features=relative_ast_path --features=swift.cacheable_swiftmodules --features=swift.index_while_building --features=swift.use_global_index_store --features=swift.use_global_module_cache --nolegacy_important_outputs --show_result=0 --noworker_sandboxing --spawn_strategy=remote,worker,local
Loading: 
Loading: 
Loading: 1 packages loaded
Analyzing: target @rules_xcodeproj_generated//generator/Telegram/Telegram_xcodeproj:Telegram_xcodeproj (2 packages loaded, 0 targets configured)
Analyzing: target @rules_xcodeproj_generated//generator/Telegram/Telegram_xcodeproj:Telegram_xcodeproj (4 packages loaded, 4393 targets configured)
INFO: Analyzed target @rules_xcodeproj_generated//generator/Telegram/Telegram_xcodeproj:Telegram_xcodeproj (4 packages loaded, 4394 targets configured).
checking cached actions
INFO: Found 1 target...
[3 / 17] [Prepa] BazelWorkspaceStatusAction stable-status.txt
ERROR: /private/var/tmp/_bazel_vakhonakashidze/4e628adf874771f087c4fbe57dff4b48/rules_xcodeproj.noindex/build_output_base/external/build_bazel_rules_swift/tools/worker/BUILD:113:10: Compiling tools/worker/worker_main.cc [for tool] failed: undeclared inclusion(s) in rule '@build_bazel_rules_swift//tools/worker:worker':
this rule is missing dependency declarations for the following files included by 'tools/worker/worker_main.cc':
'/Users/vakhonakashidze/Desktop/clocktower/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/algorithm'
'/Users/vakhonakashidze/Desktop/clocktower/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__assert'
'/Users/vakhonakashidze/Desktop/clocktower/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__config'
'/Users/vakhonakashidze/Desktop/clocktower/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__config_site'
'/Users/vakhonakashidze/Desktop/clocktower/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__verbose_abort'
'/Users/vakhonakashidze/Desktop/clocktower/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__availability'
'/Users/vakhonakashidze/Desktop/clocktower/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__debug'


...


'/Users/vakhonakashidze/Desktop/clocktower/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/sys/_types/_fd_clr.h'
'/Users/vakhonakashidze/Desktop/clocktower/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/sys/_types/_fd_zero.h'
'/Users/vakhonakashidze/Desktop/clocktower/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/sys/_types/_fd_isset.h'
'/Users/vakhonakashidze/Desktop/clocktower/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/sys/_types/_fd_copy.h'
'/Users/vakhonakashidze/Desktop/clocktower/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/sys/_types/_fsblkcnt_t.h'
'/Users/vakhonakashidze/Desktop/clocktower/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/sys/_types/_fsfilcnt_t.h'
'/Users/vakhonakashidze/Desktop/clocktower/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/_types/_nl_item.h'
'/Users/vakhonakashidze/Desktop/clocktower/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__bsd_locale_defaults.h'
'/Users/vakhonakashidze/Desktop/clocktower/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/cstdarg'
'/Users/vakhonakashidze/Desktop/clocktower/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/map'
'/Users/vakhonakashidze/Desktop/clocktower/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__tree'
INFO: Elapsed time: 3.993s, Critical Path: 0.08s
INFO: 105 processes: 105 internal.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target
Traceback (most recent call last):
File "/Users/vakhonakashidze/Projects/Telegram-iOS/build-system/Make/Make.py", line 1050, in <module>
  generate_project(bazel=bazel_path, arguments=args)
File "/Users/vakhonakashidze/Projects/Telegram-iOS/build-system/Make/Make.py", line 568, in generate_project
  generate(
File "/Users/vakhonakashidze/Projects/Telegram-iOS/build-system/Make/ProjectGeneration.py", line 58, in generate
  generate_xcodeproj(build_environment, disable_extensions, disable_provisioning_profiles, include_release, generate_dsym, configuration_path, bazel_app_arguments, target_name)
File "/Users/vakhonakashidze/Projects/Telegram-iOS/build-system/Make/ProjectGeneration.py", line 51, in generate_xcodeproj
  call_executable(bazel_generate_arguments)
File "/Users/vakhonakashidze/Projects/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 81, in call_executable
  subprocess.check_call(resolved_arguments, env=resolved_env)
File "/Users/vakhonakashidze/Desktop/clocktower/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
  raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/vakhonakashidze/Projects/Telegram-iOS/build-input/bazel-6.4.0-darwin-arm64', 'run', '//Telegram:Telegram_xcodeproj', '--override_repository=build_configuration=/Users/vakhonakashidze/Projects/Telegram-iOS/build-input/configuration-repository', '--//Telegram:disableExtensions', '--//Telegram:disableStripping']' returned non-zero exit status 1.
