### ISSUE TITLE
Unable to build MacOS 14.2.1

### ISSUE THREAD

**Issue by bclark8923** [TelegramMessenger/Telegram-iOS#1320]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Attempting to build the app and it's failing

### Actual Behavior

When I run the build I get the following error. Has anyone seen this before? I'm guesing it may be my MacOS version if nothing else comes to mind?

```
INFO: Analyzed target @rules_xcodeproj_generated//generator/Telegram/Telegram_xcodeproj:Telegram_xcodeproj (623 packages loaded, 28903 targets configured).
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_brianclark/ac3fec121ea29762a0f22a7a52eba5e4/rules_xcodeproj.noindex/build_output_base/external/build_bazel_rules_swift/tools/worker/BUILD:113:10: Compiling tools/worker/worker_main.cc [for tool] failed: undeclared inclusion(s) in rule '@build_bazel_rules_swift//tools/worker:worker':
this rule is missing dependency declarations for the following files included by 'tools/worker/worker_main.cc':
  '/Users/brianclark/Downloads/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/algorithm'
  '/Users/brianclark/Downloads/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__assert'
  '/Users/brianclark/Downloads/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__config'
  '/Users/brianclark/Downloads/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__config_site'
  '/Users/brianclark/Downloads/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__verbose_abort'
  '/Users/brianclark/Downloads/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__availability'
  '/Users/brianclark/Downloads/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__debug'
  '/Users/brianclark/Downloads/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__type_traits/is_constant_evaluated.h'
  '/Users/brianclark/Downloads/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/cstddef'
......
  '/Users/brianclark/Downloads/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/cstdarg'
  '/Users/brianclark/Downloads/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/map'
  '/Users/brianclark/Downloads/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__tree'
INFO: Elapsed time: 4.313s, Critical Path: 0.11s
INFO: 8 processes: 8 internal.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target
Traceback (most recent call last):
  File "/Users/brianclark/tracemachina/Telegram-iOS/build-system/Make/Make.py", line 1050, in <module>
    generate_project(bazel=bazel_path, arguments=args)
  File "/Users/brianclark/tracemachina/Telegram-iOS/build-system/Make/Make.py", line 568, in generate_project
    generate(
  File "/Users/brianclark/tracemachina/Telegram-iOS/build-system/Make/ProjectGeneration.py", line 58, in generate
    generate_xcodeproj(build_environment, disable_extensions, disable_provisioning_profiles, include_release, generate_dsym, configuration_path, bazel_app_arguments, target_name)
  File "/Users/brianclark/tracemachina/Telegram-iOS/build-system/Make/ProjectGeneration.py", line 51, in generate_xcodeproj
    call_executable(bazel_generate_arguments)
  File "/Users/brianclark/tracemachina/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 81, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/Users/brianclark/Downloads/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/brianclark/tracemachina/Telegram-iOS/build-input/bazel-6.4.0-darwin-arm64', 'run', '//Telegram:Telegram_xcodeproj', '--override_repository=build_configuration=/Users/brianclark/tracemachina/Telegram-iOS/build-input/configuration-repository', '--//Telegram:disableExtensions', '--//Telegram:disableStripping']' returned non-zero exit status 1.
```

**Comment by bclark8923** [comment]
> Is there any other relevant output?

Yes my bad, updated my original post with the relevant information

**Comment by ali-fareed** [comment]
I would suggest to try cloning and building the project from scratch.

**Comment by jogiking** [comment]
> > Is there any other relevant output?
> 
> Yes my bad, updated my original post with the relevant information

@bclark8923 
Did you resolve the issue? I'm experiencing the same problem.
