### ISSUE TITLE
Xcode15.2 build Fail

### ISSUE THREAD

**Issue by LSPBoy** [TelegramMessenger/Telegram-iOS#1397]
python3 build-system/Make/Make.py \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath=build-system/template_minimal_development_configuration.json \
    --xcodeManagedCodesigning
Traceback (most recent call last):
  File "/Users/apple/Desktop/Code/Telegram-iOS/build-system/Make/Make.py", line 1040, in <module>
    bazel_path = locate_bazel(base_path=os.getcwd())
  File "/Users/apple/Desktop/Code/Telegram-iOS/build-system/Make/BazelLocation.py", line 12, in locate_bazel
    versions = BuildEnvironmentVersions(base_path=os.getcwd())
  File "/Users/apple/Desktop/Code/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 130, in __init__
    configuration_dict = json.load(file)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 5 column 5 (char 68)

Xcode15.2, bazel:7.1.1 macos: Sonoma 14.3.1
How to solve it? thank you very much

**Comment by ali-fareed** [comment]
Looks like your `configuration.json` file is not a valid JSON. You should review the README and follow its instructions.
