### ISSUE TITLE
Can't generate project (Xcode 15)

### ISSUE THREAD

**Issue by Nazarash** [TelegramMessenger/Telegram-iOS#1443]
Hello. When I try to generate a project in Xcode via terminal I encounter the following error:

```bash
python3 build-system/Make/Make.py \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath=build-system/template_minimal_development_configuration.json \
    --xcodeManagedCodesigning
No matching processes were found
ERROR: /Users/user2024/Desktop/Telegram-iOS-master/WORKSPACE:11:17: fetching local_repository rule //external:rules_xcodeproj: java.io.IOException: No MODULE.bazel, REPO.bazel, or WORKSPACE file found in /Users/user2024/Desktop/Telegram-iOS-master/build-system/bazel-rules/rules_xcodeproj
ERROR: Error computing the main repository mapping: no such package '@@rules_xcodeproj//xcodeproj': No MODULE.bazel, REPO.bazel, or WORKSPACE file found in /Users/user2024/Desktop/Telegram-iOS-master/build-system/bazel-rules/rules_xcodeproj
Computing main repo mapping: 
Traceback (most recent call last):
  File "/Users/user2024/Desktop/Telegram-iOS-master/build-system/Make/Make.py", line 1048, in <module>
    generate_project(bazel=bazel_path, arguments=args)
  File "/Users/user2024/Desktop/Telegram-iOS-master/build-system/Make/Make.py", line 565, in generate_project
    generate(
  File "/Users/user2024/Desktop/Telegram-iOS-master/build-system/Make/ProjectGeneration.py", line 59, in generate
    generate_xcodeproj(build_environment, disable_extensions, disable_provisioning_profiles, include_release, generate_dsym, configuration_path, bazel_app_arguments, target_name)
  File "/Users/user2024/Desktop/Telegram-iOS-master/build-system/Make/ProjectGeneration.py", line 51, in generate_xcodeproj
    call_executable(bazel_generate_arguments)
  File "/Users/user2024/Desktop/Telegram-iOS-master/build-system/Make/BuildEnvironment.py", line 81, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/user2024/Desktop/Telegram-iOS-master/build-input/bazel-7.1.1-darwin-arm64', 'run', '//Telegram:Telegram_xcodeproj', '--override_repository=build_configuration=/Users/user2024/Desktop/Telegram-iOS-master/build-input/configuration-repository', '--//Telegram:disableExtensions', '--//Telegram:disableStripping']' returned non-zero exit status 1.
root@MacBook-Pro-N Telegram-iOS-master # brew install bazel

Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
root@MacBook-Pro-N Telegram-iOS-master # sudo -s python3 build-system/Make/Make.py \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath=build-system/template_minimal_development_configuration.json \
    --xcodeManagedCodesigning
No matching processes were found
ERROR: /Users/user2024/Desktop/Telegram-iOS-master/WORKSPACE:11:17: fetching local_repository rule //external:rules_xcodeproj: java.io.IOException: No MODULE.bazel, REPO.bazel, or WORKSPACE file found in /Users/user2024/Desktop/Telegram-iOS-master/build-system/bazel-rules/rules_xcodeproj
ERROR: Error computing the main repository mapping: no such package '@@rules_xcodeproj//xcodeproj': No MODULE.bazel, REPO.bazel, or WORKSPACE file found in /Users/user2024/Desktop/Telegram-iOS-master/build-system/bazel-rules/rules_xcodeproj
Computing main repo mapping: 
Traceback (most recent call last):
  File "/Users/user2024/Desktop/Telegram-iOS-master/build-system/Make/Make.py", line 1048, in <module>
    generate_project(bazel=bazel_path, arguments=args)
  File "/Users/user2024/Desktop/Telegram-iOS-master/build-system/Make/Make.py", line 565, in generate_project
    generate(
  File "/Users/user2024/Desktop/Telegram-iOS-master/build-system/Make/ProjectGeneration.py", line 59, in generate
    generate_xcodeproj(build_environment, disable_extensions, disable_provisioning_profiles, include_release, generate_dsym, configuration_path, bazel_app_arguments, target_name)
  File "/Users/user2024/Desktop/Telegram-iOS-master/build-system/Make/ProjectGeneration.py", line 51, in generate_xcodeproj
    call_executable(bazel_generate_arguments)
  File "/Users/user2024/Desktop/Telegram-iOS-master/build-system/Make/BuildEnvironment.py", line 81, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/user2024/Desktop/Telegram-iOS-master/build-input/bazel-7.1.1-darwin-arm64', 'run', '//Telegram:Telegram_xcodeproj', '--override_repository=build_configuration=/Users/user2024/Desktop/Telegram-iOS-master/build-input/configuration-repository', '--//Telegram:disableExtensions', '--//Telegram:disableStripping']' returned non-zero exit status 1.
root@MacBook-Pro-N Telegram-iOS-master #

**Comment by Nazarash** [comment]
My [template_minimal_development_configuration.json]

{
	"bundle_id": "org.{04accb7703}.Telegram",
	"api_id": "{33}",
	"api_hash": "{6869cb81bd}",
	"team_id": "{B95Q2",
	"app_center_id": "0",
	"is_internal_build": "true",
	"is_appstore_build": "false",
	"appstore_id": "0",
	"app_specific_url_scheme": "tg",
	"premium_iap_product_id": "",
	"enable_siri": false,
	"enable_icloud": false,
	"sg_config": ""
}

**Comment by Nazarash** [comment]
It's Xcode 15.2, macOS Sonoma 14.5

**Comment by Nazarash** [comment]
@ali-fareed

**Comment by Nazarash** [comment]
@ali-fareed, can you help please?

**Comment by e11iot-1337** [comment]
Thank!

**Comment by without2002** [comment]
try 'git submodule update --init --recursive' before run make.py
