### ISSUE TITLE
Build failed version 7.3.1

### ISSUE THREAD

**Issue by twisturn** [TelegramMessenger/Telegram-iOS#468]
I built XCode project using bazel (point 5 at README),, but getting this error:

FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "build-system/Make/Make.py", line 485, in <module>
    build(arguments=args)
  File "build-system/Make/Make.py", line 324, in build
    bazel_command_line.invoke_build()
  File "build-system/Make/Make.py", line 224, in invoke_build
    call_executable(combined_arguments)
  File "/Users/zj/Desktop/tg-7.3/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 60, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)

**Comment by ali-fareed** [comment]
Please post the complete log if possible.

**Comment by ali-fareed** [comment]
Feel free to reopen the issue if it still occurs.

**Comment by twisturn** [comment]
I built XCode project using bazel (point 5 at README):
python3 build-system/Make/Make.py \
    --bazel="$HOME/bazel-dist/bazel" \
    --cacheDir="$HOME/telegram-bazel-cache" \
    build \
    --configurationPath="$HOME/telegram-configuration" \
    --buildNumber=100001 \
    --configuration=release_universal
, but getting this error:

FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "build-system/Make/Make.py", line 485, in <module>
    build(arguments=args)
  File "build-system/Make/Make.py", line 324, in build
    bazel_command_line.invoke_build()
  File "build-system/Make/Make.py", line 224, in invoke_build
    call_executable(combined_arguments)
  File "/Users/zj/Desktop/tg-7.3/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 60, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/zj/bazel-dist/bazel', 'build', 'Telegram/Telegram', '--override_repository=build_configuration=/Users/zj/telegram-configuration', '--announce_rc', '--features=swift.use_global_module_cache', '--verbose_failures', '--features=swift.split_derived_files_generation', '--features=swift.skip_function_bodies_for_derived_files', '--jobs=16', '--define=buildNumber=100001', '--define=telegramVersion=7.3.1', '--disk_cache=/Users/zj/telegram-bazel-cache', '-c', 'opt', '--ios_multi_cpus=armv7,arm64', '--watchos_cpus=armv7k,arm64_32', '--apple_generate_dsym', '--output_groups=+dsyms', '--features=swift.opt_uses_wmo', '--features=swift.opt_uses_osize', '--swiftcopt=-num-threads', '--swiftcopt=0', '--features=dead_strip', '--objc_enable_binary_stripping', '--apple_bitcode=watchos=embedded']' returned non-zero exit status 1.
