### ISSUE TITLE
Built v7.4.1 failed

### ISSUE THREAD

**Issue by zerxon** [TelegramMessenger/Telegram-iOS#478]
Built v7.4.1 failed, 
Build script:
```
python3 build-system/Make/Make.py \
    --bazel="$HOME/bazel-dist/bazel" \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath="$HOME/telegram-configuration" \
    --disableExtensions \
    --disableProvisioningProfiles
```

The logs:
```
INFO: Analyzed target //:tulsi (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:tulsi up-to-date:
  bazel-bin/tulsi.zip
INFO: Elapsed time: 0.179s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
[Syslog] Tulsi CLI: version 0.20210106.88
[Syslog] Create project: Telegram
[Syslog] Fetching bazel path info
[Info] Running /Users/test/Documents/Telegram-iOS/build-input/gen/project/bazel info '--override_repository=tulsi=/Users/wallace/Library/Application Support/Tulsi/0.20210106.88/Bazel'
[Syslog] ** Completed bazel_get_package_path in 0.2132s
[Syslog] ** Completed get_package_path in 0.2144s
[Syslog] Fetching rules for packages ["Telegram"]
[Info] Running /Users/test/Documents/Telegram-iOS/build-input/gen/project/bazel --max_idle_secs=60 query '--override_repository=tulsi=/Users/wallace/Library/Application Support/Tulsi/0.20210106.88/Bazel' --announce_rc --noimplicit_deps --order_output=no --noshow_loading_progress --noshow_progress 'kind(rule, Telegram:all)' --output xml
[Syslog] ** Completed bazel_query_fetch_rules in 0.1780s
[Syslog] ** Completed fetch_rules in 0.2049s
[Syslog] Create config: Telegram
[Syslog] Tulsi CLI: version 0.20210106.88
Generating project into '/Users/test/Documents/Telegram-iOS/build-input/gen/project' using:
	config at '/Users/test/Documents/Telegram-iOS/build-input/gen/project/Telegram.tulsiproj/Configs/Telegram.tulsigen'
	Bazel workspace at '/Users/test/Documents/Telegram-iOS'
	Bazel at '/Users/test/Documents/Telegram-iOS/build-input/gen/project/bazel'.
This may take a while.
[Syslog] Fetching bazel path info
[Info] Running /Users/test/Documents/Telegram-iOS/build-input/gen/project/bazel info '--override_repository=tulsi=/Users/wallace/Library/Application Support/Tulsi/0.20210106.88/Bazel'
[Syslog] ** Completed bazel_get_package_path in 0.1646s
[Syslog] ** Completed get_package_path in 0.1657s
[Info] Build Events JSON file at "/var/folders/rw/k1ysk58553j65_04z2g3gmf40000gn/T/build_events_3955.json"
[Syslog] Extracting info for 1 rules
[Info] Running /Users/test/Documents/Telegram-iOS/build-input/gen/project/bazel build --announce_rc --show_result=0 --noshow_loading_progress --noshow_progress --symlink_prefix=/ --override_repository=build_configuration=/Users/wallace/telegram-configuration --//Telegram:disableExtensions --//Telegram:disableProvisioningProfiles --override_repository=build_configuration=/Users/wallace/telegram-configuration --announce_rc --features=swift.use_global_module_cache --verbose_failures --features=swift.enable_batch_mode --swiftcopt=-j3 --define=buildNumber=10000 --define=telegramVersion=7.4.1 --disk_cache=/Users/wallace/telegram-bazel-cache --//Telegram:disableExtensions --apple_platform_type=ios --cpu=ios_x86_64 --watchos_cpus=i386 --announce_rc '--override_repository=tulsi=/Users/wallace/Library/Application Support/Tulsi/0.20210106.88/Bazel' --compilation_mode=dbg --define=apple.add_debugger_entitlement=1 --define=apple.propagate_embedded_extra_outputs=1 --define=apple.experimental.tree_artifact_outputs=1 --features=debug_prefix_map_pwd_is_dot --tool_tag=tulsi:generator --build_event_json_file=/var/folders/rw/k1ysk58553j65_04z2g3gmf40000gn/T/build_events_3955.json --noexperimental_build_event_json_file_path_conversion --noexpand_test_suites --features=-parse_headers --experimental_run_validations=0 --aspects @tulsi//:tulsi/tulsi_aspects.bzl%tulsi_sources_aspect --output_groups=tulsi_info,-_,-default //Telegram:Telegram
[Syslog] ** Completed bazel_extract_source_info in 2108.8799s
[Error] Failed to retrieve information about the Bazel workspace. This usually means that the contents of a BUILD file are incorrect or flags are missing. Read the message log carefully for details. ERROR: An error occurred during the fetch of repository 'cmake_tar_gz':
ERROR: /Users/test/Documents/Telegram-iOS/third-party/yasm/BUILD:3:8: //third-party/yasm:yasm depends on @cmake_tar_gz//file:file in repository @cmake_tar_gz which failed to fetch. no such package '@cmake_tar_gz//file': java.io.IOException: Error downloading [https://github.com/Kitware/CMake/releases/download/v3.19.2/cmake-3.19.2-macos-universal.tar.gz] to /private/var/tmp/_bazel_wallace/16c6ffd872c0f1e3e8ba6d64c53eb353/external/cmake_tar_gz/file/downloaded: GET returned 403 Forbidden
ERROR: Analysis of aspect '@tulsi//:tulsi/tulsi_aspects.bzl%tulsi_sources_aspect of //Telegram:Telegram' failed; build aborted: Analysis failed
[Syslog] ** Completed generating_project in 2108.8887s
[Error] Project generation failed.
[Debug] Printing Bazel logs that could contain the error.
[Info] Log of Bazel aspect info output follows:
[Info] Bazel command info:
/Users/test/Documents/Telegram-iOS/build-input/gen/project/bazel build --announce_rc --show_result=0 --noshow_loading_progress --noshow_progress --symlink_prefix=/ --override_repository=build_configuration=/Users/wallace/telegram-configuration --//Telegram:disableExtensions --//Telegram:disableProvisioningProfiles --override_repository=build_configuration=/Users/wallace/telegram-configuration --announce_rc --features=swift.use_global_module_cache --verbose_failures --features=swift.enable_batch_mode --swiftcopt=-j3 --define=buildNumber=10000 --define=telegramVersion=7.4.1 --disk_cache=/Users/wallace/telegram-bazel-cache --//Telegram:disableExtensions --apple_platform_type=ios --cpu=ios_x86_64 --watchos_cpus=i386 --announce_rc '--override_repository=tulsi=/Users/wallace/Library/Application Support/Tulsi/0.20210106.88/Bazel' --compilation_mode=dbg --define=apple.add_debugger_entitlement=1 --define=apple.propagate_embedded_extra_outputs=1 --define=apple.experimental.tree_artifact_outputs=1 --features=debug_prefix_map_pwd_is_dot --tool_tag=tulsi:generator --build_event_json_file=/var/folders/rw/k1ysk58553j65_04z2g3gmf40000gn/T/build_events_3955.json --noexperimental_build_event_json_file_path_conversion --noexpand_test_suites --features=-parse_headers --experimental_run_validations=0 --aspects @tulsi//:tulsi/tulsi_aspects.bzl%tulsi_sources_aspect --output_groups=tulsi_info,-_,-default //Telegram:Telegram
Exited with code 1

INFO: Invocation ID: 4cb536a5-fa7e-4047-a136-a5382bc220b0
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'build' from /Users/test/Documents/Telegram-iOS/.bazelrc:
  'build' options: --action_env=ZERO_AR_DATE=1 --apple_platform_type=ios --cxxopt=-std=c++14 --per_file_copt=third-party/webrtc/.*.cpp$,@-std=c++14 --per_file_copt=third-party/webrtc/.*.cc$,@-std=c++14 --per_file_copt=third-party/webrtc/.*.mm$,@-std=c++14 --features=debug_prefix_map_pwd_is_dot --features=swift.cacheable_swiftmodules --features=swift.debug_prefix_map --features=swift.enable_vfsoverlays --strategy=Genrule=standalone --spawn_strategy=standalone --strategy=SwiftCompile=standalone
INFO: Repository cmake_tar_gz instantiated at:
  /Users/test/Documents/Telegram-iOS/WORKSPACE:54:10: in <toplevel>
Repository rule http_file defined at:
  /private/var/tmp/_bazel_wallace/16c6ffd872c0f1e3e8ba6d64c53eb353/external/bazel_tools/tools/build_defs/repo/http.bzl:426:28: in <toplevel>
WARNING: Download from https://github.com/Kitware/CMake/releases/download/v3.19.2/cmake-3.19.2-macos-universal.tar.gz failed: class java.io.IOException GET returned 403 Forbidden
ERROR: An error occurred during the fetch of repository 'cmake_tar_gz':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_wallace/16c6ffd872c0f1e3e8ba6d64c53eb353/external/bazel_tools/tools/build_defs/repo/http.bzl", line 150, column 33, in _http_file_impl
		download_info = ctx.download(
Error in download: java.io.IOException: Error downloading [https://github.com/Kitware/CMake/releases/download/v3.19.2/cmake-3.19.2-macos-universal.tar.gz] to /private/var/tmp/_bazel_wallace/16c6ffd872c0f1e3e8ba6d64c53eb353/external/cmake_tar_gz/file/downloaded: GET returned 403 Forbidden
ERROR: /Users/test/Documents/Telegram-iOS/third-party/yasm/BUILD:3:8: //third-party/yasm:yasm depends on @cmake_tar_gz//file:file in repository @cmake_tar_gz which failed to fetch. no such package '@cmake_tar_gz//file': java.io.IOException: Error downloading [https://github.com/Kitware/CMake/releases/download/v3.19.2/cmake-3.19.2-macos-universal.tar.gz] to /private/var/tmp/_bazel_wallace/16c6ffd872c0f1e3e8ba6d64c53eb353/external/cmake_tar_gz/file/downloaded: GET returned 403 Forbidden
ERROR: Analysis of aspect '@tulsi//:tulsi/tulsi_aspects.bzl%tulsi_sources_aspect of //Telegram:Telegram' failed; build aborted: Analysis failed
INFO: Elapsed time: 2108.844s
INFO: 0 processes.
INFO: Build Event Protocol files produced successfully.

[Error] Generate[FAIL]: 2108.8894s General failure: Bazel aspects could not be built.
Xcode project generation failed
Traceback (most recent call last):
  File "/Users/test/Documents/Telegram-iOS/build-system/Make/Make.py", line 502, in <module>
    generate_project(arguments=args)
  File "/Users/test/Documents/Telegram-iOS/build-system/Make/Make.py", line 315, in generate_project
    generate(
  File "/Users/test/Documents/Telegram-iOS/build-system/Make/ProjectGeneration.py", line 119, in generate
    call_executable([
  File "/Users/test/Documents/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 60, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/test/Documents/Telegram-iOS/build-input/gen/project/Tulsi.app/Contents/MacOS/Tulsi', '--', '--verbose', '--genconfig', '/Users/test/Documents/Telegram-iOS/build-input/gen/project/Telegram.tulsiproj:Telegram', '--bazel', '/Users/test/Documents/Telegram-iOS/build-input/gen/project/bazel', '--outputfolder', '/Users/test/Documents/Telegram-iOS/build-input/gen/project', '--no-open-xcode']' returned non-zero exit status 15.
```

Who can hlep? Thanks

**Comment by ali-fareed** [comment]
It looks like the build system could not download the CMake binary (it says "GET returned 403 Forbidden"). It may be a temporary issue somewhere between you and Github, please try again.
