### ISSUE TITLE
Compilation failed in real device

### ISSUE THREAD

**Issue by zerxon** [TelegramMessenger/Telegram-iOS#490]
It was generated the project with the scripts:
```
python3 build-system/Make/Make.py \
    --bazel="$HOME/bazel-dist/bazel" \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath="$HOME/telegram-configuration" \
    --disableExtensions \
    --disableProvisioningProfiles
```

It runs well on Simulator,  but when it be compiled in real phone get the blew errors:

The error log:
```
/Users/test/Telegram-iOS/Telegram/BUILD:1537:16: error: in ios_application rule //Telegram:Telegram: 
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_wallace/16c6ffd872c0f1e3e8ba6d64c53eb353/external/build_bazel_rules_apple/apple/internal/ios_rules.bzl", line 273, column 41, in _ios_application_impl
		processor_result = processor.process(
	File "/private/var/tmp/_bazel_wallace/16c6ffd872c0f1e3e8ba6d64c53eb353/external/build_bazel_rules_apple/apple/internal/processor.bzl", line 650, column 36, in _process
		partial_outputs = [partial.call(p, ctx = ctx) for p in partials]
	File "/private/var/tmp/_bazel_wallace/16c6ffd872c0f1e3e8ba6d64c53eb353/external/bazel_skylib/lib/partial.bzl", line 38, column 28, in _call
		return partial.function(*function_args, **function_kwargs)
	File "/private/var/tmp/_bazel_wallace/16c6ffd872c0f1e3e8ba6d64c53eb353/external/build_bazel_rules_apple/apple/internal/partials/provisioning_profile.bzl", line 42, column 13, in _provisioning_profile_partial_impl
		fail(
Error in fail: ERROR: In //Telegram:Telegram:
Building for device, but no provisioning_profile attribute was set.
error: Analysis of target '//Telegram:Telegram' failed; build aborted: Analysis of target '//Telegram:Telegram' failed
note: Elapsed time: 19.373s
note: 0 processes.
error: Build did NOT complete successfully (293 packages loaded, 19144 targets configured)
<*> Running Bazel completed in 19592.659 ms
/Users/test/Telegram-iOS/build-input/gen/project/Telegram.xcodeproj/.tulsi/Scripts/bazel_build.py:581: error: Bazel build failed with exit code 1. Please check the build log in Report Navigator (⌘9) for more information.
<*> Everything completed in 19625.215 ms
```

**Comment by ali-fareed** [comment]
`--disableProvisioningProfiles` has to be off for real device deployment. It's a debugging feature that makes it possible to compile and run the app in a simulator without the need to generate all the numerous certificates.

**Comment by zerxon** [comment]
> `--disableProvisioningProfiles` has to be off for real device deployment. It's a debugging feature that makes it possible to compile and run the app in a simulator without the need to generate all the numerous certificates.

But I have set the Signing args in Signing & Capability Tab, neither it works.

**Comment by ali-fareed** [comment]
The settings inside Xcode are irrelevant and should not be changed manually. The app is built and signed using Bazel.
