### ISSUE TITLE
build for iphone with error

### ISSUE THREAD

**Issue by FranZhou** [TelegramMessenger/Telegram-iOS#539]
Showing Recent Messages
/Users/franzhou/telegram-ios/Telegram/BUILD:1676:16: In ios_application rule //Telegram:Telegram:

Traceback (most recent call last):

	File "/private/var/tmp/_bazel_franzhou/e7c130dd92838a8fa9f8d286c43fbfc4/external/build_bazel_rules_apple/apple/internal/ios_rules.bzl", line 289, column 41, in _ios_application_impl

		processor_result = processor.process(

	File "/private/var/tmp/_bazel_franzhou/e7c130dd92838a8fa9f8d286c43fbfc4/external/build_bazel_rules_apple/apple/internal/processor.bzl", line 692, column 36, in _process

		partial_outputs = [partial.call(p) for p in partials]

	File "/private/var/tmp/_bazel_franzhou/e7c130dd92838a8fa9f8d286c43fbfc4/external/bazel_skylib/lib/partial.bzl", line 38, column 28, in _call

		return partial.function(*function_args, **function_kwargs)

	File "/private/var/tmp/_bazel_franzhou/e7c130dd92838a8fa9f8d286c43fbfc4/external/build_bazel_rules_apple/apple/internal/partials/provisioning_profile.bzl", line 40, column 13, in _provisioning_profile_partial_impl

		fail(

Error in fail: ERROR: In //Telegram:Telegram:

Building for device, but no provisioning_profile attribute was set.

Analysis of target '//Telegram:Telegram' failed; build aborted: Analysis of target '//Telegram:Telegram' failed

Elapsed time: 0.323s

0 processes.

Build did NOT complete successfully (0 packages loaded, 0 targets configured)

<*> Running Bazel completed in 440.243 ms

/Users/franzhou/telegram-ios/build-input/gen/project/Telegram.xcodeproj/.tulsi/Scripts/bazel_build.py:581: Bazel build failed with exit code 1. Please check the build log in Report Navigator (⌘9) for more information.

Simulator build and run success
but my iPhone 12 can't run 

### Environment
**Device:** `iPhone 12`

**iOS version**: `14.X`

**App version:** `7.7`

**Comment by ali-fareed** [comment]
You need to follow step 4 in README ("Adjust configuration parameters").

**Comment by tboxSol** [comment]
@ali-fareed  didn't work
