### ISSUE TITLE
Bazel unknown argument: '-disallow-use-new-driver'

### ISSUE THREAD

**Issue by shivanraptor** [TelegramMessenger/Telegram-iOS#672]
When building release-8.2.2, Bazel returns an error:

> unknown argument: '-disallow-use-new-driver'

Using Bazel version 4.0.0, macOS 10.15.7, Xcode 12.4

Build log is as follow:

```
% python3 build-system/Make/Make.py --overrideBazelVersion --overrideXcodeVersion --bazel="$HOME/bazel-dist/bazel" --cacheDir="/Volumes/MainArchive/telegram-bazel-cache" build --configurationPath="$HOME/telegram-configuration" --buildNumber=11051 --configuration=release_universal
Overriding the required Xcode version 13.0 with 12.4 as reported by 'xcode-select -p'
TelegramBuild: running
/Users/adv/bazel-dist/bazel build Telegram/Telegram --override_repository=build_configuration=/Users/adv/telegram-configuration --announce_rc --features=swift.use_global_module_cache --verbose_failures --features=swift.skip_function_bodies_for_derived_files --jobs=8 --define=buildNumber=11051 --define=telegramVersion=8.2.2 --features=swift.split_derived_files_generation --disk_cache=/Volumes/MainArchive/telegram-bazel-cache -c opt --ios_multi_cpus=armv7,arm64 --watchos_cpus=armv7k,arm64_32 --apple_generate_dsym --output_groups=+dsyms --features=swift.opt_uses_wmo --features=swift.opt_uses_osize --swiftcopt=-num-threads --swiftcopt=0 --features=dead_strip --objc_enable_binary_stripping --apple_bitcode=watchos=embedded
Starting local Bazel server and connecting to it...
INFO: Invocation ID: e82a2bfa-f306-4327-b3c6-dfa968eff271
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=166
INFO: Reading rc options for 'build' from /Volumes/MainArchive/xCodeProjects/Telegram_v8.2.2/Telegram-iOS/.bazelrc:
  'build' options: --action_env=ZERO_AR_DATE=1 --apple_platform_type=ios --cxxopt=-std=c++14 --per_file_copt=third-party/webrtc/.*.cpp$,@-std=c++14 --per_file_copt=third-party/webrtc/.*.cc$,@-std=c++14 --per_file_copt=third-party/webrtc/.*.mm$,@-std=c++14 --per_file_copt=submodules/LottieMeshSwift/LottieMeshBinding/Sources/.*.mm$,@-std=c++14 --swiftcopt=-disallow-use-new-driver --features=debug_prefix_map_pwd_is_dot --features=swift.cacheable_swiftmodules --features=swift.debug_prefix_map --features=swift.enable_vfsoverlays --strategy=Genrule=standalone --spawn_strategy=standalone --strategy=SwiftCompile=standalone --define RULES_SWIFT_BUILD_DUMMY_WORKER=1
INFO: Analyzed target //Telegram:Telegram (308 packages loaded, 21550 targets configured).
INFO: Found 1 target...
ERROR: /Volumes/MainArchive/xCodeProjects/Telegram_v8.2.2/Telegram-iOS/submodules/SSignalKit/SwiftSignalKit/BUILD:3:14: Generating derived files for Swift module SwiftSignalKit failed: (Exit 1): worker failed: error executing command 
  (cd /private/var/tmp/_bazel_adv/d491597a031d63bfb533b160242c3403/execroot/__main__ && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneOS \
    APPLE_SDK_VERSION_OVERRIDE=14.4 \
    XCODE_VERSION_OVERRIDE=12.4.0.12D4e \
  bazel-out/host/bin/external/build_bazel_rules_swift/tools/worker/worker swiftc @bazel-out/ios-armv7-min9.0-applebin_ios-ios_armv7-opt-ST-36ad1e8d6baf/bin/submodules/SSignalKit/SwiftSignalKit/SwiftSignalKit.swiftmodule-0.params)
Execution platform: @local_config_platform//:host
<unknown>:0: error: unknown argument: '-disallow-use-new-driver'
Target //Telegram:Telegram failed to build
INFO: Elapsed time: 50.028s, Critical Path: 15.98s
INFO: 167 processes: 61 internal, 106 local.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "build-system/Make/Make.py", line 627, in <module>
    build(arguments=args)
  File "build-system/Make/Make.py", line 423, in build
    bazel_command_line.invoke_build()
  File "build-system/Make/Make.py", line 314, in invoke_build
    call_executable(combined_arguments)
  File "/Volumes/MainArchive/xCodeProjects/Telegram_v8.2.2/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 60, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/Users/adv/opt/anaconda3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/adv/bazel-dist/bazel', 'build', 'Telegram/Telegram', '--override_repository=build_configuration=/Users/adv/telegram-configuration', '--announce_rc', '--features=swift.use_global_module_cache', '--verbose_failures', '--features=swift.skip_function_bodies_for_derived_files', '--jobs=8', '--define=buildNumber=11051', '--define=telegramVersion=8.2.2', '--features=swift.split_derived_files_generation', '--disk_cache=/Volumes/MainArchive/telegram-bazel-cache', '-c', 'opt', '--ios_multi_cpus=armv7,arm64', '--watchos_cpus=armv7k,arm64_32', '--apple_generate_dsym', '--output_groups=+dsyms', '--features=swift.opt_uses_wmo', '--features=swift.opt_uses_osize', '--swiftcopt=-num-threads', '--swiftcopt=0', '--features=dead_strip', '--objc_enable_binary_stripping', '--apple_bitcode=watchos=embedded']' returned non-zero exit status 1.
```

Any clue?

**Comment by shivanraptor** [comment]
After I commented out the line with the flag in `.bazelrc`, the compile process continues, but encountered another issue:

```
ERROR: /Volumes/MainArchive/xCodeProjects/Telegram_v8.2.2/Telegram-iOS/submodules/TelegramCore/BUILD:3:14: Generating derived files for Swift module TelegramCore failed: (Exit 1): worker failed: error executing command 
  (cd /private/var/tmp/_bazel_adv/d491597a031d63bfb533b160242c3403/execroot/__main__ && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneOS \
    APPLE_SDK_VERSION_OVERRIDE=14.4 \
    XCODE_VERSION_OVERRIDE=12.4.0.12D4e \
  bazel-out/host/bin/external/build_bazel_rules_swift/tools/worker/worker swiftc @bazel-out/ios-armv7-min9.0-applebin_ios-ios_armv7-opt-ST-36ad1e8d6baf/bin/submodules/TelegramCore/TelegramCore.swiftmodule-0.params)
Execution platform: @local_config_platform//:host
submodules/TelegramCore/Sources/Settings/ContentSettings.swift:19:99: error: cast from 'JSONElement?' to unrelated type '[String]' always fails
        if let data = appConfiguration.data, let reasonsData = data["ignore_restriction_reasons"] as? [String] {
                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^   ~~~~~~~~
submodules/TelegramCore/Sources/Suggestions.swift:31:88: error: cast from 'JSONElement?' to unrelated type '[String]' always fails
        guard let data = appConfiguration.data, let list = data["pending_suggestions"] as? [String] else {
                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^   ~~~~~~~~
Target //Telegram:Telegram failed to build
INFO: Elapsed time: 211.892s, Critical Path: 155.35s
INFO: 742 processes: 56 internal, 686 local.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "build-system/Make/Make.py", line 627, in <module>
    build(arguments=args)
  File "build-system/Make/Make.py", line 423, in build
    bazel_command_line.invoke_build()
  File "build-system/Make/Make.py", line 314, in invoke_build
    call_executable(combined_arguments)
  File "/Volumes/MainArchive/xCodeProjects/Telegram_v8.2.2/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 60, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/Users/adv/opt/anaconda3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/adv/bazel-dist/bazel', 'build', 'Telegram/Telegram', '--override_repository=build_configuration=/Users/adv/telegram-configuration', '--announce_rc', '--features=swift.use_global_module_cache', '--verbose_failures', '--features=swift.skip_function_bodies_for_derived_files', '--jobs=8', '--define=buildNumber=11051', '--define=telegramVersion=8.2.2', '--features=swift.split_derived_files_generation', '--disk_cache=/Volumes/MainArchive/telegram-bazel-cache', '-c', 'opt', '--ios_multi_cpus=armv7,arm64', '--watchos_cpus=armv7k,arm64_32', '--apple_generate_dsym', '--output_groups=+dsyms', '--features=swift.opt_uses_wmo', '--features=swift.opt_uses_osize', '--swiftcopt=-num-threads', '--swiftcopt=0', '--features=dead_strip', '--objc_enable_binary_stripping', '--apple_bitcode=watchos=embedded']' returned non-zero exit status 1.
```

Seems it's a Swift syntax error? It doesn't make sense, since the source code shouldn't have problems. Please help.

**Comment by shivanraptor** [comment]
Found that it only happens in Xcode 12.4. Works fine in Xcode 13. Any workaround?

**Comment by ali-fareed** [comment]
The project is guaranteed to build using specific Xcode and bazel versions (see versions.json).

**Comment by shivanraptor** [comment]
> The project is guaranteed to build using specific Xcode and bazel versions (see versions.json).

Do you mean Xcode 12.4 is no longer supported? But my Mac is too old to install Xcode 13 (cannot upgrade macOS)

**Comment by ali-fareed** [comment]
Correct, it uses APIs that are only available in Xcode 13/iOS 15.
