### ISSUE TITLE
Buck encountered an internal error java.lang.UnsatisfiedLinkError: Unable to load library 'CoreWLAN': Native library (darwin/libCoreWLAN.dylib) not found in resource path

### ISSUE THREAD

**Issue by zhongliIOS** [TelegramMessenger/Telegram-iOS#764]
When I build .ipa in Paralles. Xcode13 .Get a error. How Can I fixed it. If anyone know it.Please mention me.
Thanks a lot.

Buck encountered an internal error
java.lang.UnsatisfiedLinkError: Unable to load library 'CoreWLAN': Native library (darwin/libCoreWLAN.dylib) not found in resource path ([file:/Users/telegram/telegram-ios/.buckd/resources/605b4735a5995d91850b336dbb5967ff131e4198/buck_server])
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:303)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:427)
	at com.sun.jna.Library$Handler.<init>(Library.java:179)
	at com.sun.jna.Native.loadLibrary(Native.java:569)
	at com.sun.jna.Native.loadLibrary(Native.java:544)
	at com.facebook.buck.util.environment.MacWifiSsidFinder.<clinit>(MacWifiSsidFinder.java:38)
	at com.facebook.buck.util.environment.NetworkInfo.getWifiSsid(NetworkInfo.java:77)
	at com.facebook.buck.util.environment.DefaultExecutionEnvironment.getWifiSsid(DefaultExecutionEnvironment.java:78)
	at com.facebook.buck.cli.MainRunner.runMainWithExitCode(MainRunner.java:1152)
	at com.facebook.buck.cli.MainRunner.runMainThenExit(MainRunner.java:478)
	at com.facebook.buck.cli.MainWithoutNailgun.main(MainWithoutNailgun.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.facebook.buck.cli.bootstrapper.ClassLoaderBootstrapper.main(ClassLoaderBootstrapper.java:55)

**Comment by ali-fareed** [comment]
Buck is not used in this project.
