### ISSUE TITLE
App Build Error

### ISSUE THREAD

**Issue by tangcici** [TelegramMessenger/Telegram-iOS#777]
I get an error when I execute the script:
python3 build-system/Make/Make.py
--bazel="$HOME/bazel-dist/bazel"
--cacheDir="$HOME/telegram-bazel-cache"
build
--configurationPath="$HOME/telegram-configuration"
--buildNumber=100001
--configuration=release_universal

```
ERROR: /Users/tangxixi/Telegram-iOS/third-party/yasm/BUILD:3:8: Executing genrule //third-party/yasm:yasm [for host] failed: (Exit 1): bash failed: error executing command
  (cd /private/var/tmp/_bazel_tangxixi/4b5a3b4727c85c15d5eee07fa212148a/execroot/__main__ && \
  exec env - \
    PATH=/usr/bin:/bin:/usr/sbin:/sbin \
  /bin/bash -c source external/bazel_tools/tools/genrule/genrule-setup.sh;
set -x
    core_count="sysctl -n hw.logicalcpu"
    BUILD_DIR="bazel-out/host/bin/third-party/yasm/build"
    rm -rf "$BUILD_DIR"
    mkdir -p "$BUILD_DIR"

    CMAKE_DIR="$(pwd)/$BUILD_DIR/cmake"
    rm -rf "$CMAKE_DIR"
    mkdir -p "$CMAKE_DIR"
    tar -xf "external/cmake_tar_gz/file/downloaded" -C "$CMAKE_DIR"

    tar -xzf "third-party/yasm/yasm-1.3.0.tar.gz" --directory "$BUILD_DIR"
    pushd "$BUILD_DIR/yasm-1.3.0"
    mkdir build
    cd build
    PATH="$PATH:$CMAKE_DIR/cmake-3.19.2-macos-universal/CMake.app/Contents/bin" cmake .. -DYASM_BUILD_TESTS=OFF -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF
    make -j $core_count
    popd

    tar -cf "bazel-out/host/bin/third-party/yasm/yasm.tar" -C "$BUILD_DIR/yasm-1.3.0/build" .
')
# Configuration: caf237710b9a3e91ac5f5f2e72e64a137bdddc0a52b6c96425ca47f57a048b70
# Execution platform: @local_config_platform//:host
++ sysctl -n hw.logicalcpu
+ core_count=8
+ BUILD_DIR=bazel-out/host/bin/third-party/yasm/build
+ rm -rf bazel-out/host/bin/third-party/yasm/build
+ mkdir -p bazel-out/host/bin/third-party/yasm/build
++ pwd
+ CMAKE_DIR=/private/var/tmp/_bazel_tangxixi/4b5a3b4727c85c15d5eee07fa212148a/execroot/__main__/bazel-out/host/bin/third-party/yasm/build/cmake
+ rm -rf /private/var/tmp/_bazel_tangxixi/4b5a3b4727c85c15d5eee07fa212148a/execroot/__main__/bazel-out/host/bin/third-party/yasm/build/cmake
+ mkdir -p /private/var/tmp/_bazel_tangxixi/4b5a3b4727c85c15d5eee07fa212148a/execroot/__main__/bazel-out/host/bin/third-party/yasm/build/cmake
+ tar -xf external/cmake_tar_gz/file/downloaded -C /private/var/tmp/_bazel_tangxixi/4b5a3b4727c85c15d5eee07fa212148a/execroot/__main__/bazel-out/host/bin/third-party/yasm/build/cmake
+ tar -xzf third-party/yasm/yasm-1.3.0.tar.gz --directory bazel-out/host/bin/third-party/yasm/build
+ pushd bazel-out/host/bin/third-party/yasm/build/yasm-1.3.0
+ mkdir build
+ cd build
+ PATH=/usr/bin:/bin:/usr/sbin:/sbin:/private/var/tmp/_bazel_tangxixi/4b5a3b4727c85c15d5eee07fa212148a/execroot/__main__/bazel-out/host/bin/third-party/yasm/build/cmake/cmake-3.19.2-macos-universal/CMake.app/Contents/bin
+ cmake .. -DYASM_BUILD_TESTS=OFF -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF
CMake Deprecation Warning at CMakeLists.txt:2 (CMAKE_MINIMUM_REQUIRED):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Error at ConfigureChecks.cmake:39 (MESSAGE):
  Could not find Python executable
Call Stack (most recent call first):
  CMakeLists.txt:36 (INCLUDE)


/private/var/tmp/_bazel_tangxixi/4b5a3b4727c85c15d5eee07fa212148a/execroot/__main__/bazel-out/host/bin/third-party/yasm/build/yasm-1.3.0 /private/var/tmp/_bazel_tangxixi/4b5a3b4727c85c15d5eee07fa212148a/execroot/__main__
-- The C compiler identification is AppleClang 13.1.6.13160021
-- The CXX compiler identification is AppleClang 13.1.6.13160021
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for locale.h
-- Looking for locale.h - found
-- Looking for libgen.h
-- Looking for libgen.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for direct.h
-- Looking for direct.h - not found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for abort
-- Looking for abort - found
-- Looking for getcwd
-- Looking for getcwd - found
-- Looking for toascii
-- Looking for toascii - found
-- Looking for dlopen in dl
-- Looking for dlopen in dl - found
-- Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE)
-- Configuring incomplete, errors occurred!
See also "/private/var/tmp/_bazel_tangxixi/4b5a3b4727c85c15d5eee07fa212148a/execroot/__main__/bazel-out/host/bin/third-party/yasm/build/yasm-1.3.0/build/CMakeFiles/CMakeOutput.log".
See also "/private/var/tmp/_bazel_tangxixi/4b5a3b4727c85c15d5eee07fa212148a/execroot/__main__/bazel-out/host/bin/third-party/yasm/build/yasm-1.3.0/build/CMakeFiles/CMakeError.log".
Target //Telegram:Telegram failed to build
ERROR: /Users/tangxixi/Telegram-iOS/submodules/StickerPackPreviewUI/BUILD:3:14 Generating derived files for Swift module //submodules/StickerPackPreviewUI:StickerPackPreviewUI failed: (Exit 1): bash failed: error executing command
  (cd /private/var/tmp/_bazel_tangxixi/4b5a3b4727c85c15d5eee07fa212148a/execroot/__main__ && \
  exec env - \
    PATH=/usr/bin:/bin:/usr/sbin:/sbin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh;
set -x
    core_count="`sysctl -n hw.logicalcpu`"
    BUILD_DIR="bazel-out/host/bin/third-party/yasm/build"
    rm -rf "$BUILD_DIR"
    mkdir -p "$BUILD_DIR"

    CMAKE_DIR="$(pwd)/$BUILD_DIR/cmake"
    rm -rf "$CMAKE_DIR"
    mkdir -p "$CMAKE_DIR"
    tar -xf "external/cmake_tar_gz/file/downloaded" -C "$CMAKE_DIR"

    tar -xzf "third-party/yasm/yasm-1.3.0.tar.gz" --directory "$BUILD_DIR"
    pushd "$BUILD_DIR/yasm-1.3.0"
    mkdir build
    cd build
    PATH="$PATH:$CMAKE_DIR/cmake-3.19.2-macos-universal/CMake.app/Contents/bin" cmake .. -DYASM_BUILD_TESTS=OFF -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF
    make -j $core_count
    popd

    tar -cf "bazel-out/host/bin/third-party/yasm/yasm.tar" -C "$BUILD_DIR/yasm-1.3.0/build" .
')
# Configuration: caf237710b9a3e91ac5f5f2e72e64a137bdddc0a52b6c96425ca47f57a048b70
# Execution platform: @local_config_platform//:host
INFO: Elapsed time: 48.134s, Critical Path: 11.73s
INFO: 850 processes: 848 internal, 2 local.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "build-system/Make/Make.py", line 728, in <module>
    build(bazel=bazel_path, arguments=args)
  File "build-system/Make/Make.py", line 482, in build
    bazel_command_line.invoke_build()
  File "build-system/Make/Make.py", line 328, in invoke_build
    call_executable(combined_arguments)
  File "/Users/tangxixi/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 60, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/tangxixi/bazel-dist/bazel', 'build', 'Telegram/Telegram', '--override_repository=build_configuration=/Users/tangxixi/telegram-configuration', '--announce_rc', '--verbose_failures', '--features=swift.skip_function_bodies_for_derived_files', '--jobs=8', '--define=buildNumber=100001', '--define=telegramVersion=8.7', '--features=swift.split_derived_files_generation', '--disk_cache=/Users/tangxixi/telegram-bazel-cache', '-c', 'opt', '--ios_multi_cpus=armv7,arm64', '--watchos_cpus=armv7k,arm64_32', '--apple_generate_dsym', '--output_groups=+dsyms', '--features=swift.opt_uses_wmo', '--features=swift.opt_uses_osize', '--swiftcopt=-num-threads', '--swiftcopt=0', '--features=dead_strip', '--objc_enable_binary_stripping', '--apple_bitcode=watchos=embedded']' returned non-zero exit status 1. `
```

**Environment**
Xcode version: 13.3.1

MacOS version: 12.3.1

Telegram Build Version: 8.7.1

**Comment by xuchaofei** [comment]
哥们儿  你这个xcode版本不对    得用13.2.1的xcode版本

**Comment by shivanraptor** [comment]
> 哥们儿 你这个xcode版本不对 得用13.2.1的xcode版本

Please use English.

**Comment by ali-fareed** [comment]
See https://github.com/TelegramMessenger/Telegram-iOS/issues/783

**Comment by zudian** [comment]
> 哥们儿 你这个xcode版本不对 得用13.2.1的xcode版本

 哥们能请教几个问题不？

**Comment by MrGuoZiHao** [comment]
How do it?

**Comment by 670047255** [comment]
> > 哥们儿 你这个xcode版本不对 得用13.2.1的xcode版本
> 
> 哥们能请教几个问题不？

哥们，我也想请教几个问题
