### ISSUE TITLE
syntax errors

### ISSUE THREAD

**Issue by Skytechw** [TelegramMessenger/Telegram-iOS#842]
### Checklist
- [x ] I am reporting an issue in existing functionality that does not work as intended
- [ ] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
im trying to compile the app but every time I got some syntax errors.

**python3 build-system/Make/Make.py \
    --bazel="$HOME/bazel-dist/bazel" \
    --cacheDir="$HOME/telegram-bazel-cache" \
    build \
    --configurationPath="$HOME/telegram-configuration" \
    --buildNumber=100001 \
    --configuration=release_universal**
    
TelegramBuild: running
/Users/skytechw/bazel-dist/bazel build Telegram/Telegram --override_repository=build_configuration=/Users/skytechw/telegram-configuration --announce_rc --features=swift.use_global_module_cache --verbose_failures --features=swift.skip_function_bodies_for_derived_files --jobs=8 --define=buildNumber=100001 --define=telegramVersion=8.9 --features=swift.split_derived_files_generation --disk_cache=/Users/skytechw/telegram-bazel-cache -c opt --ios_multi_cpus=armv7,arm64 --watchos_cpus=armv7k,arm64_32 --apple_generate_dsym --output_groups=+dsyms --features=swift.opt_uses_wmo --features=swift.opt_uses_osize --swiftcopt=-num-threads --swiftcopt=0 --features=dead_strip --objc_enable_binary_stripping --apple_bitcode=watchos=embedded
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 2163bab4-c30d-4a6f-a59e-d1e2fbd550f2
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=80
INFO: Reading rc options for 'build' from /Users/skytechw/Telegram-iOS/.bazelrc:
  'build' options: --action_env=ZERO_AR_DATE=1 --apple_platform_type=ios --cxxopt=-std=c++17 --per_file_copt=third-party/webrtc/.*.cpp$,@-std=c++17 --per_file_copt=third-party/webrtc/.*.cc$,@-std=c++17 --per_file_copt=third-party/webrtc/.*.mm$,@-std=c++17 --per_file_copt=submodules/LottieMeshSwift/LottieMeshBinding/Sources/.*.mm$,@-std=c++17 --swiftcopt=-whole-module-optimization --features=debug_prefix_map_pwd_is_dot --features=swift.cacheable_swiftmodules --features=swift.debug_prefix_map --features=swift.enable_vfsoverlays --strategy=Genrule=standalone --spawn_strategy=standalone --strategy=SwiftCompile=standalone --define RULES_SWIFT_BUILD_DUMMY_WORKER=1
ERROR: /private/var/tmp/_bazel_skytechw/c90cef87b66ae6aeb48e0a41614a5063/external/build_bazel_rules_swift/swift/internal/compiling.bzl:752:17: 'lambda' not supported, declare a function instead
ERROR: /private/var/tmp/_bazel_skytechw/c90cef87b66ae6aeb48e0a41614a5063/external/build_bazel_rules_swift/swift/internal/compiling.bzl:752:17: syntax error at 'lambda': expected expression
ERROR: /private/var/tmp/_bazel_skytechw/c90cef87b66ae6aeb48e0a41614a5063/external/build_bazel_rules_swift/swift/internal/compiling.bzl:762:17: 'lambda' not supported, declare a function instead
ERROR: /private/var/tmp/_bazel_skytechw/c90cef87b66ae6aeb48e0a41614a5063/external/build_bazel_rules_swift/swift/internal/compiling.bzl:976:21: 'lambda' not supported, declare a function instead
ERROR: /private/var/tmp/_bazel_skytechw/c90cef87b66ae6aeb48e0a41614a5063/external/build_bazel_rules_swift/swift/internal/compiling.bzl:976:21: syntax error at 'lambda': expected expression
ERROR: /private/var/tmp/_bazel_skytechw/c90cef87b66ae6aeb48e0a41614a5063/external/build_bazel_rules_swift/swift/internal/compiling.bzl:285:9: nested functions are not allowed. Move the function to the top level.
ERROR: /private/var/tmp/_bazel_skytechw/c90cef87b66ae6aeb48e0a41614a5063/external/build_bazel_rules_swift/swift/internal/compiling.bzl:751:29: contains syntax errors
ERROR: /private/var/tmp/_bazel_skytechw/c90cef87b66ae6aeb48e0a41614a5063/external/build_bazel_rules_swift/swift/internal/compiling.bzl:761:29: contains syntax errors
ERROR: /private/var/tmp/_bazel_skytechw/c90cef87b66ae6aeb48e0a41614a5063/external/build_bazel_rules_swift/swift/internal/compiling.bzl:975:33: contains syntax errors
ERROR: /private/var/tmp/_bazel_skytechw/c90cef87b66ae6aeb48e0a41614a5063/external/build_bazel_rules_swift/swift/internal/compiling.bzl:994:33: contains syntax errors
ERROR: Skipping 'Telegram/Telegram': error loading package 'Telegram': in /private/var/tmp/_bazel_skytechw/c90cef87b66ae6aeb48e0a41614a5063/external/build_bazel_rules_swift/swift/swift.bzl: in /private/var/tmp/_bazel_skytechw/c90cef87b66ae6aeb48e0a41614a5063/external/build_bazel_rules_swift/swift/internal/swift_common.bzl: Extension 'swift/internal/compiling.bzl' has errors
WARNING: Target pattern parsing failed.
ERROR: error loading package 'Telegram': in /private/var/tmp/_bazel_skytechw/c90cef87b66ae6aeb48e0a41614a5063/external/build_bazel_rules_swift/swift/swift.bzl: in /private/var/tmp/_bazel_skytechw/c90cef87b66ae6aeb48e0a41614a5063/external/build_bazel_rules_swift/swift/internal/swift_common.bzl: Extension 'swift/internal/compiling.bzl' has errors
INFO: Elapsed time: 4.663s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
Traceback (most recent call last):
  File "/Users/skytechw/Telegram-iOS/build-system/Make/Make.py", line 728, in <module>
    build(bazel=bazel_path, arguments=args)
  File "/Users/skytechw/Telegram-iOS/build-system/Make/Make.py", line 482, in build
    bazel_command_line.invoke_build()
  File "/Users/skytechw/Telegram-iOS/build-system/Make/Make.py", line 328, in invoke_build
    call_executable(combined_arguments)
  File "/Users/skytechw/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 60, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/skytechw/bazel-dist/bazel', 'build', 'Telegram/Telegram', '--override_repository=build_configuration=/Users/skytechw/telegram-configuration', '--announce_rc', '--features=swift.use_global_module_cache', '--verbose_failures', '--features=swift.skip_function_bodies_for_derived_files', '--jobs=8', '--define=buildNumber=100001', '--define=telegramVersion=8.9', '--features=swift.split_derived_files_generation', '--disk_cache=/Users/skytechw/telegram-bazel-cache', '-c', 'opt', '--ios_multi_cpus=armv7,arm64', '--watchos_cpus=armv7k,arm64_32', '--apple_generate_dsym', '--output_groups=+dsyms', '--features=swift.opt_uses_wmo', '--features=swift.opt_uses_osize', '--swiftcopt=-num-threads', '--swiftcopt=0', '--features=dead_strip', '--objc_enable_binary_stripping', '--apple_bitcode=watchos=embedded']' returned non-zero exit status 1.

### Environment
macOS 12.6
bazel 4.0
Xcode 14.0

**Comment by ali-fareed** [comment]
Please try following the steps in README first.

**Comment by Skytechw** [comment]
I did

**Comment by ali-fareed** [comment]
The recommended steps do not include using a custom bazel installation.

Additionally, it may be necessary to use the exact Xcode version (see `versions.json`) to be able to build the app. The current app version (8.9) does not support building with Xcode 14.
