### ISSUE TITLE
If it runs, run and report an error

### ISSUE THREAD

**Issue by Bowewn** [TelegramMessenger/Telegram-iOS#906]
INFO: Analyzed target //:tulsi (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /Users/bowen/Documents/Telegram-iOS/build-system/tulsi/BUILD:61:18: StoryboardCompile tulsi-intermediates/Base.lproj_storyboardc/Main.storyboardc failed: (Exit 1): xctoolrunner failed: error executing command 
  (cd /private/var/tmp/_bazel_bowen/cf334e96c66c2efb346a851723609077/execroot/__main__ && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=12.3 \
    XCODE_VERSION_OVERRIDE=14.0.0.14A309 \
  bazel-out/darwin_arm64-opt-exec-2B5CBBC6-ST-ee81979272f8/bin/external/build_bazel_rules_apple/tools/xctoolrunner/xctoolrunner ibtool --compilation-directory '[ABSOLUTE]bazel-out/applebin_macos-darwin_x86_64-fastbuild-ST-4d5b244fa833/bin/tulsi-intermediates/Base.lproj_storyboardc' --minimum-deployment-target 10.13 --target-device mac --module Tulsi '[ABSOLUTE]src/Tulsi/Base.lproj/Main.storyboard')
# Configuration: 1d709c737226c4efb85b8dc7e68f69d1051dd58ba93cc22fe2d9e2a0aafe5150
# Execution platform: @local_config_platform//:host
Error occurred while attempting to use the default Python toolchain (@rules_python//python:autodetecting_toolchain).
Could not get interpreter version via '/usr/local/bin/python3 -V'
Target //:tulsi failed to build
INFO: Elapsed time: 0.532s, Critical Path: 0.43s
INFO: 9 processes: 9 internal.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "/Users/bowen/Documents/Telegram-iOS/build-system/Make/Make.py", line 1005, in <module>
    generate_project(bazel=bazel_path, arguments=args)
  File "/Users/bowen/Documents/Telegram-iOS/build-system/Make/Make.py", line 556, in generate_project
    generate(
  File "/Users/bowen/Documents/Telegram-iOS/build-system/Make/ProjectGeneration.py", line 46, in generate
    call_executable(tulsi_build_command)
  File "/Users/bowen/Documents/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 81, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/bowen/bin/bazel', 'build', '//:tulsi', '--xcode_version=14.0', '--use_top_level_targets_for_symlinks', '--verbose_failures', '--swiftcopt=-whole-module-optimization']' returned non-zero exit status 1.

**Comment by Bowewn** [comment]
INFO: Elapsed time: 145.426s, Critical Path: 5.09s
INFO: 60 processes: 46 internal, 14 darwin-sandbox.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "/Users/bowen/Documents/Telegram-iOS/build-system/Make/Make.py", line 1005, in <module>
    generate_project(bazel=bazel_path, arguments=args)
  File "/Users/bowen/Documents/Telegram-iOS/build-system/Make/Make.py", line 556, in generate_project
    generate(
  File "/Users/bowen/Documents/Telegram-iOS/build-system/Make/ProjectGeneration.py", line 46, in generate
    call_executable(tulsi_build_command)
  File "/Users/bowen/Documents/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 81, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/bowen/bin/bazel', 'build', '//:tulsi', '--xcode_version=14.0', '--use_top_level_targets_for_symlinks', '--verbose_failures', '--swiftcopt=-whole-module-optimization']' returned non-zero exit status 1.

**Comment by tboxSol** [comment]
how to fix?

**Comment by DreadIron** [comment]
The hell stop mailing me every 20 seconds
