### ISSUE TITLE
打包报错

### ISSUE THREAD

**Issue by tuyongjiang** [TelegramMessenger/Telegram-iOS#926]
打包命令
python3 build-system/Make/Make.py \
    --overrideXcodeVersion \
    --cacheDir="$HOME/telegram-bazel-cache" \
    build \
     --buildNumber=100001  \
    --configurationPath="$HOME/telegram-configuration/development-configuration.json"  \
    --codesigningInformationPath "$HOME/telegram-configuration/fake-codesigning" \
    --configuration=release_universal

报错
ERROR: /Users/tt/Desktop/Telegram/Telegram-iOS/Telegram/BUILD:1578:14: no such target '@build_configuration//provisioning:Intents.mobileprovision': target 'Intents.mobileprovision' not declared in package 'provisioning' defined by /private/var/tmp/_bazel_tt/33b801b4dd16469bbea27d0e1fd3000e/external/build_configuration/provisioning/BUILD and referenced by '//Telegram:IntentsExtension'
ERROR: Analysis of target '//Telegram:Telegram' failed; build aborted: 

问下这是什么问题

**Comment by andrew-nemtsev** [comment]
What is contents of your
$HOME/telegram-configuration/development-configuration.json
file?

**Comment by tuyongjiang** [comment]
> What is contents of your
> $HOME/telegram-configuration/development-configuration.json
> file?

this contents
{
	"bundle_id": "skutelegram",
	"api_id": "8",
	"api_hash": "7245de8e747a0d6fbe11f7cc14fcc0bb",
	"team_id": "6AC73ATNX7",
	"app_center_id": "0",
	"is_internal_build": "false",
	"is_appstore_build": "true",
	"appstore_id": "686449807",
	"app_specific_url_scheme": "tg",
	"premium_iap_product_id": "org.telegram.telegramPremium.monthly",
	"enable_siri": true,
	"enable_icloud": true
}

**Comment by culturetown** [comment]
你找到了解决方法了吗？我也遇到了差不多的问题。
ERROR: /Users/mac/Telegram-iOS/Telegram/BUILD:1442:14: no such target '@build_configuration//provisioning:Widget.mobileprovision': target 'Widget.mobileprovision' not declared in package 'provisioning' defined by /private/var/tmp/_bazel_mac/8b97eaf40c33077446fb30720c9517a2/external/build_configuration/provisioning/BUILD and referenced by '//Telegram:WidgetExtension'
ERROR: Analysis of target '//Telegram:Telegram' failed; build aborted:

**Comment by culturetown** [comment]
谢谢，经过你的提醒，检查了下，ipa打出来了。

**Comment by L-Jay** [comment]
请教一下我这是什么问题，build总是失败，看错误不是证书的问题，应该还没到那一步，像是bezel的问题，但是我生成工程成功了，说明bazel的配置是可以的，也可以在模拟器运行，非常感谢
ERROR: /Users/cuizhiwei/Telegram-iOS/Telegram/BUILD:1448:14: Processing and signing WidgetExtension failed: (Exit 1): process-and-sign--1295105435.sh failed: error executing command
  (cd /private/var/tmp/_bazel_cuizhiwei/479f096fd2df96e568bd6419ddfeec24/execroot/__main__ && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneOS \
    APPLE_SDK_VERSION_OVERRIDE=16.2 \
    XCODE_VERSION_OVERRIDE=14.2.0.14C18 \
  bazel-out/applebin_ios-ios_armv7-opt-ST-5b7531beec20/bin/Telegram/WidgetExtension-intermediates/process-and-sign--1295105435.sh should_sign should_process should_compress)
# Configuration: b71b7dff908cdab1dd992ca03ed9f51db64fea0f6d8f221ba573cf8408042a04
# Execution platform: @local_config_platform//:host
ERROR: Unable to find an identity on the system matching the ones in external/build_configuration/provisioning/Widget.mobileprovision
Target //Telegram:Telegram failed to build
INFO: Elapsed time: 47.100s, Critical Path: 15.04s
INFO: 4494 processes: 3396 disk cache hit, 1044 internal, 54 local.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "/Users/cuizhiwei/Telegram-iOS/build-system/Make/Make.py", line 1035, in <module>
    build(bazel=bazel_path, arguments=args)
  File "/Users/cuizhiwei/Telegram-iOS/build-system/Make/Make.py", line 600, in build
    bazel_command_line.invoke_build()
  File "/Users/cuizhiwei/Telegram-iOS/build-system/Make/Make.py", line 369, in invoke_build
    call_executable(combined_arguments)
  File "/Users/cuizhiwei/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 81, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/cuizhiwei/bin/bazel', 'build', 'Telegram/Telegram', '--override_repository=build_configuration=/Users/cuizhiwei/Telegram-iOS/build-input/configuration-repository', '--announce_rc', '--features=swift.use_global_module_cache', '--verbose_failures', '--experimental_remote_cache_async', '--features=swift.skip_function_bodies_for_derived_files', '--jobs=8', '--define=buildNumber=100001', '--define=telegramVersion=9.4.1', '--disk_cache=/Users/cuizhiwei/telegram-bazel-cache', '-c', 'opt', '--ios_multi_cpus=armv7,arm64', '--watchos_cpus=arm64_32', '--apple_generate_dsym', '--output_groups=+dsyms', '--features=swift.opt_uses_wmo', '--features=swift.opt_uses_osize', '--swiftcopt=-num-threads', '--swiftcopt=1', '--swiftcopt=-j1', '--features=dead_strip', '--objc_enable_binary_stripping', '--apple_bitcode=watchos=embedded']' returned non-zero exit status 1.

**Comment by caicaibuchicai** [comment]
> 谢谢，经过你的提醒，检查了下，ipa打出来了。

ipa 打包的时候，是把9个证书都配置了一遍吗？有能自定义证书配置的方法没有？就是把不需要的证书屏蔽掉。

**Comment by tuyongjiang** [comment]
> Unable to find an identity on the system matching the ones in external/build_configuration/provisioning/Widget.mobileprovision

Unable to find an identity on the system matching the ones in external/build_configuration/provisioning/Widget.mobileprovision. 证书问题

**Comment by tuyongjiang** [comment]
> > 谢谢，经过你的提醒，检查了下，ipa打出来了。
> 
> ipa 打包的时候，是把9个证书都配置了一遍吗？有能自定义证书配置的方法没有？就是把不需要的证书屏蔽掉。

我是都配置,然后打包.

**Comment by xionghx** [comment]
> > > 谢谢，经过你的提醒，检查了下，ipa打出来了。
> > 
> > 
> > ipa 打包的时候，是把9个证书都配置了一遍吗？有能自定义证书配置的方法没有？就是把不需要的证书屏蔽掉。
> 
> 我是都配置,然后打包.

我想请教一下你的证书是怎么配置的,盼复为感!

**Comment by df1228** [comment]
@tuyongjiang 求付费指导下，个人资料页有联系方式，谢谢！

**Comment by xionghx** [comment]
> @tuyongjiang 求付费指导下，个人资料页有联系方式，谢谢！

我配好了,编译通过

**Comment by xq312704108** [comment]
> 你找到了解决方法了吗？我也遇到了差不多的问题。 ERROR: /Users/mac/Telegram-iOS/Telegram/BUILD:1442:14: no such target '@build_configuration//provisioning:Widget.mobileprovision': target 'Widget.mobileprovision' not declared in package 'provisioning' defined by /private/var/tmp/_bazel_mac/8b97eaf40c33077446fb30720c9517a2/external/build_configuration/provisioning/BUILD and referenced by '//Telegram:WidgetExtension' ERROR: Analysis of target '//Telegram:Telegram' failed; build aborted:

证书应该怎么配置 求指导啊

**Comment by xionghx** [comment]
我能提供支持

On Jan 24, 2024, at 15:36, xq312704108 ***@***.***> wrote:



你找到了解决方法了吗？我也遇到了差不多的问题。 ERROR: /Users/mac/Telegram-iOS/Telegram/BUILD:1442:14: no such target ***@***.***_configuration//provisioning:Widget.mobileprovision': target 'Widget.mobileprovision' not declared in package 'provisioning' defined by /private/var/tmp/_bazel_mac/8b97eaf40c33077446fb30720c9517a2/external/build_configuration/provisioning/BUILD and referenced by '//Telegram:WidgetExtension' ERROR: Analysis of target '//Telegram:Telegram' failed; build aborted:

证书应该怎么配置 求指导啊
