### ISSUE TITLE
想真机调试，generateProject时报错，生成不了Xcode项目。

### ISSUE THREAD

**Issue by kevinmou** [TelegramMessenger/Telegram-iOS#999]
我生成了我自己的Profile描述文件，并且替换到了provisioning文件夹下和fake-codesigning/profiles下。
![e6b390d360b16ed056082ed336a28cf3](https://user-images.githubusercontent.com/3231578/218251886-dbcd37a8-29c0-4343-acfe-5de9c45469ee.png)

wwb@wwbdeMacBook-Pro Telegram-iOS % python3 build-system/Make/Make.py \
    --overrideXcodeVersion \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath="$HOME/telegram-configuration/development-configuration.json"  \
    --codesigningInformationPath "$HOME/telegram-configuration/fake-codesigning" \
    --disableExtensions  
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 47.1M  100 47.1M    0     0  22996      0  0:35:48  0:35:48 --:--:-- 33771
Traceback (most recent call last):
  File "/Users/wwb/Telegram-iOS/build-system/Make/Make.py", line 1033, in <module>
    generate_project(bazel=bazel_path, arguments=args)
  File "/Users/wwb/Telegram-iOS/build-system/Make/Make.py", line 532, in generate_project
    resolve_configuration(
  File "/Users/wwb/Telegram-iOS/build-system/Make/Make.py", line 489, in resolve_configuration
    codesigning_data = resolve_codesigning(
  File "/Users/wwb/Telegram-iOS/build-system/Make/Make.py", line 463, in resolve_codesigning
    profile_source.copy_profiles_to_destination(destination_path=provisioning_profiles_path)
  File "/Users/wwb/Telegram-iOS/build-system/Make/BuildConfiguration.py", line 305, in copy_profiles_to_destination
    copy_profiles_from_directory(source_path=self.directory_path + '/profiles', destination_path=destination_path, team_id=self.team_id, bundle_id=self.bundle_id)
  File "/Users/wwb/Telegram-iOS/build-system/Make/BuildConfiguration.py", line 182, in copy_profiles_from_directory
    profile_dict = plistlib.loads(profile_data)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/plistlib.py", line 883, in loads
    return load(fp, fmt=fmt, dict_type=dict_type)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/plistlib.py", line 875, in load
    return p.parse(fp)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/plistlib.py", line 177, in parse
    self.parser.ParseFile(fileobj)
  File "/System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot2/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/python3/python3-124/Python/Modules/pyexpat.c", line 461, in EndElement
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/plistlib.py", line 195, in handle_end_element
    handler()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/plistlib.py", line 236, in end_key
    raise ValueError("unexpected key at line %d" %
ValueError: unexpected key at line 168

**Comment by ali-fareed** [comment]
Could you share the contents of `$HOME/telegram-configuration/fake-codesigning/profiles"?

**Comment by caicaibuchicai** [comment]
$HOME/telegram-configuration/fake-codesigning 看下这个下面的文件有没有
